apiVersion: apps/v1
kind: Deployment
metadata:
  name: gophers-on-azure
  labels:
    app: gophers-on-azure
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  gophers-on-azure
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gophers-on-azure
    spec:
      nodeSelector:
        agentpool: userpool1
      containers:
        - name: gophers-on-azure
          image: 'shipyard.azurecr.io/gophers-on-azure:latest'
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gophers-on-azure
  labels:
    app: gophers-on-azure
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: gophers-on-azure