# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    make deps
    make image
- script: |
    docker login -u $(acr_user) -p $(acr_pass)
    docker push adcaline/gophers-on-azure
